#' Class to Store Simulation Parameters
#'
#' An S4 class for storing simulation parameters  
#' used to generate synthetic RNA-seq count data.
#'
#' @slot n_subgenomes An integer representing the number of subgenomes.
#' @slot n_genes An integer representing the number of genes or homeologs.
#' @slot n_groups An integer representing the number of experimental groups.
#' @slot n_replicates An integer representing the number of replicates per group.
#' @slot params_population A data frame containing population-level mean
#'          and dispersion values used for sampling.
#' @slot params A data frame containing sampled mean and dispersion values  
#'          used to generate artificial count data.
#' @slot nls An object generated by `nls()`  
#'          for modeling dispersion or variance as a function of the mean.
#' @slot mu A matrix of true mean expression values
#'          of the artificial count data.
#' @slot her A matrix of true homeolog expression ratios
#'          of the artificial count data.
#' @return An object of class \code{SimParams}.
#' @seealso [sim_homeolog_counts()]
#' @exportClass SimParams
setClass("SimParams",
         slots = c(
             n_subgenomes = "numeric",
             n_genes = "numeric",
             n_groups = "numeric",
             n_replicates = "numeric",
             
             params_population = "data.frame",
             params = "data.frame",
             nls = "ANY",
             
             mu = "ListOrMatrix",
             her = "ListOrMatrix"
         ))
